"""Self-Healing loop.

After codegen, run `tsc --noEmit` over the generated app. If it fails, collect
the errors, ask the LLM to propose a patched file, apply it, and retry — up to
`self_heal_max_attempts` times.

We deliberately bound the blast radius: the healer only replaces individual
files it is explicitly asked about, and never invents new files.
"""

from __future__ import annotations

import asyncio
import json
import re
from pathlib import Path

from .config import settings
from .llm import OllamaError, generate_json

HEAL_SYSTEM = """You are Aura's Self-Healing engine. You receive a single
TypeScript/React file and a TypeScript compiler error produced while
building it. Return JSON of the form:
  {"path": "<same path>", "content": "<full replacement file>"}
Output ONLY JSON. Do not include prose. Preserve all imports and existing
behaviour; make the smallest possible change to fix the error."""


async def _run(cmd: list[str], cwd: Path, timeout: int) -> tuple[int, str, str]:
    proc = await asyncio.create_subprocess_exec(
        *cmd,
        cwd=str(cwd),
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=timeout)
    except asyncio.TimeoutError:
        proc.kill()
        return 124, "", f"timeout after {timeout}s"
    return proc.returncode or 0, stdout.decode(errors="replace"), stderr.decode(errors="replace")


async def typecheck(app_dir: Path) -> tuple[bool, str]:
    """Run `npx tsc --noEmit` if node_modules exist; otherwise a syntax sanity pass."""
    if (app_dir / "node_modules").exists():
        code, out, err = await _run(
            ["npx", "--no-install", "tsc", "--noEmit"],
            app_dir,
            settings.self_heal_timeout_seconds,
        )
        return code == 0, (out + err).strip()
    # No deps installed (common in tests). Do a minimal syntax check on every
    # .ts/.tsx file we generated by loading them into a TS parser if available,
    # otherwise just verify files are non-empty. This is a best-effort gate.
    issues: list[str] = []
    for p in app_dir.rglob("*.ts*"):
        if p.stat().st_size == 0:
            issues.append(f"empty file: {p.relative_to(app_dir)}")
    return (not issues), "\n".join(issues)


_ERR_FILE_RE = re.compile(r"^(?P<path>[^\s(]+\.tsx?)[(\s:](?P<rest>.*)$", re.M)


def _first_error_file(stderr: str, app_dir: Path) -> Path | None:
    for m in _ERR_FILE_RE.finditer(stderr):
        candidate = (app_dir / m.group("path")).resolve()
        try:
            candidate.relative_to(app_dir.resolve())
        except ValueError:
            continue
        if candidate.exists():
            return candidate
    return None


async def heal(app_dir: Path) -> tuple[bool, list[dict]]:
    """Run typecheck → heal → repeat. Returns (success, attempts_log)."""
    attempts: list[dict] = []
    for i in range(1, settings.self_heal_max_attempts + 1):
        ok, output = await typecheck(app_dir)
        attempts.append({"attempt": i, "ok": ok, "output": output[-2000:]})
        if ok:
            return True, attempts

        target = _first_error_file(output, app_dir)
        if not target:
            return False, attempts

        src = target.read_text()
        prompt = (
            f"Path: {target.relative_to(app_dir)}\n\n"
            f"Compiler/lint output:\n{output[-1500:]}\n\n"
            f"Current file:\n```\n{src}\n```"
        )
        try:
            patched = await generate_json(prompt, system=HEAL_SYSTEM)
        except OllamaError as e:
            attempts[-1]["heal_error"] = str(e)
            return False, attempts

        new_content = patched.get("content")
        if not isinstance(new_content, str) or not new_content.strip():
            attempts[-1]["heal_error"] = "LLM returned no content"
            return False, attempts

        target.write_text(new_content)
        attempts[-1]["patched"] = str(target.relative_to(app_dir))

    return False, attempts
